
baseURL = 'https://dev.ispecookay.com/'
languageCode = 'en-us'
title = 'Is PECO Okay?'
theme = 'peco'

enableRobotsTXT = true


#
# Set up our API endpoint for substitution in Javascript.
#
[params]
env = "dev"
apiEndpointBase = "https://api.dev.ispecookay.com"

