
baseURL = 'https://dev.ispecookay.com/'
languageCode = 'en-us'
title = 'Is PECO Okay?'
theme = 'peco'

enableRobotsTXT = true


#
# Set up our API endpoint for substitution in Javascript.
#
[params]
env = "test"
apiEndpointBase = "https://g278mi62k3.execute-api.us-east-1.amazonaws.com/"

