#
# Note to self: I'm not actually using the Serverless integration on their site,
# it turns out that streaming logs is super expensive, relatively speaking.
# I was looking at about $6/mo, which is more than the rest of my AWS bill combined.
#
org: dmuth
app: peco
service: peco-api
frameworkVersion: '3'

provider:
  name: aws

  # This is a faster method, and will be the default in Serverless 4
  deploymentMethod: direct

  runtime: python3.10

  # Don't keep old versions of functions.
  versionFunctions: false

  # Cloudwatch log retention for 30 days
  logRetentionInDays: 30

  environment:
    STAGE: ${sls:stage}

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:custom.dynamoTableName}" 

  stackTags:
    project: "peco"
    stage: "${sls:stage}"

  httpApi:
    cors: true


functions:

  test:
    handler: api/testing.main
    #url: true
    #events:
    #  - httpApi:
    #      path: /test
    #      method: get

  #
  # This function fetches the latest PECO statuses from DynamoDB.
  #
  peco:
    handler: api/peco.get_status
    events:
      - httpApi:
          path: /peco
          method: get

  #
  # Get recent status.  At this time, the default is 12 (1 hour).
  #
  peco_recent:
    handler: api/peco.get_status_recent
    events:
      - httpApi: 
          path: /peco/recent
          method: get

  #
  # Live status from PECO (for testing/development purposes)
  #
  peco_live:
    handler: api/peco.get_status_live
    #events: # Debugging
    #  - httpApi: 
    #      path: /peco/live
    #      method: get


  #
  # This function fetches PECO's status periodically and writes it to 
  # a DynamoDB table.
  #
  cron:
    handler: api/cron.main
    events:
      - schedule: 
          rate: rate(1 minute)
          enabled: true
      #- httpApi: # Debugging
      #    path: /cron
      #    method: get


#
# Our resources are in CloudFormation syntax
#
resources:

  Resources:
    #
    # DynanoDB table for storing data.
    #
    # This is, BTW, raw CloudFormation config right here.
    #
    pecoOutagesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        #
        # If I mess around with the indexes, I will have to briefly rename this table
        # to something else, deploy, then change the name back and deploy a second time.
        #
        # If I don't do that, Serverless (or CloudFlare) doesn't properly pick up 
        # what I'm trying to do and will throw an error when it tries to delete 
        # a non-existant table.
        #
        # What a stupid bug.
        #
        TableName: ${self:custom.dynamoTableName}

        # Set to on-demand capacity mode
        BillingMode: PAY_PER_REQUEST  

        # Prevent accidental deletion
        DeletionProtectionEnabled: true

        #
        # Set up our attribute definitions for the Partition Key and Sort Key.
        #
        AttributeDefinitions:
          - AttributeName: Date
            AttributeType: S
          - AttributeName: DateTime
            AttributeType: S
          - AttributeName: Hour
            AttributeType: N

        KeySchema:
          - AttributeName: Date
            KeyType: HASH
          - AttributeName: DateTime
            KeyType: RANGE

        LocalSecondaryIndexes:
          - IndexName: Hour
            KeySchema:
            - AttributeName: Date
              KeyType: HASH
            - AttributeName: Hour
              KeyType: RANGE
            Projection:
              NonKeyAttributes: 
                - humanized
              ProjectionType: INCLUDE

        PointInTimeRecoverySpecification:
          PointInTimeRecoveryEnabled: true

    #
    # Create our bucket.  Public access is blocked by default.
    #
    AssetsBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: dmuth-peco-${sls:stage}


plugins:
  - serverless-python-requirements
  #
  # https://www.serverless.com/plugins/serverless-plugin-resource-tagging
  #
  - serverless-plugin-resource-tagging
  #
  # Used to sync our static assets to S3. 
  #
  # https://www.serverless.com/plugins/serverless-s3-sync
  #
  - serverless-s3-sync


custom:

  stage: "${sls:stage}"
  dynamoTableName: "peco-outages-${sls:stage}"

  s3Sync:
    #
    # Don't deploy when doing "sls deploy", require "sls s3sync" instead.
    #
    noSync: true

    buckets:
    - bucketName: dmuth-peco-${sls:stage}
      localDir: hugo/public
      deleteRemoved: true




