service: peco-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.9

functions:

  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

  peco:
    handler: handler.get_peco_status
    events:
      - httpApi:
          path: /peco
          method: get

plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  serverless-offline:
    httpPort: 3333

