org: dmuth
app: peco
service: peco-api
frameworkVersion: '3'

provider:
  name: aws
  # This is a faster method, and will be the default in Serverless 4
  deploymentMethod: direct
  runtime: python3.9
  # Don't keep old versions of functions.
  versionFunctions: false


functions:

  hello:
    handler: handler.hello
    #url: true
    events:
      - httpApi:
          path: /
          method: get

  peco:
    handler: handler.get_peco_status
    #url: true
    events:
      - httpApi:
          path: /peco
          method: get

  cron:
    handler: cron.main
    events:
      - schedule: 
          rate: rate(1 minute)
          enabled: true

plugins:
  - serverless-offline
  - serverless-python-requirements
  # https://www.serverless.com/plugins/serverless-finch
  - serverless-finch


custom:
  serverless-offline:
    httpPort: 3333

  # Deploy static assets with "sls client deploy"
  client:
    bucketName: dmuth-test-serverless-${sls:stage}
    distributionFolder: assets
 

